"""Shared embedding client for dense + sparse (BM25) vector generation.

Consolidated from src/ingestion/embedding.py. All plans use this single client.
"""

from __future__ import annotations

import os
import logging
from openai import OpenAI

logger = logging.getLogger("pick.storage.embedding")

# ── Config ────────────────────────────────────────────────────────────

EMBEDDING_MODEL = os.environ.get("EMBEDDING_MODEL", "doubao-embedding-text")
EMBEDDING_DIM = int(os.environ.get("EMBEDDING_DIM", "1024"))
LLM_BASE_URL = os.environ.get("LLM_BASE_URL", "")
EMBEDDING_BASE_URL = os.environ.get("EMBEDDING_BASE_URL", LLM_BASE_URL)
LLM_API_KEY = os.environ.get("LLM_API_KEY", "sk-placeholder")
EMBEDDING_API_KEY = os.environ.get("EMBEDDING_API_KEY", LLM_API_KEY)

_client: OpenAI | None = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(
            base_url=EMBEDDING_BASE_URL or None,
            api_key=EMBEDDING_API_KEY,
        )
    return _client


def embed_texts(texts: list[str], *, client: OpenAI | None = None) -> list[list[float]]:
    """Generate dense embeddings for a list of texts.

    Returns a list of float vectors, one per input text.
    """
    if not texts:
        return []
    if client is None:
        client = _get_client()
    try:
        resp = client.embeddings.create(
            model=EMBEDDING_MODEL,
            input=texts,
        )
        return [d.embedding for d in resp.data]
    except Exception:
        logger.exception("Embedding failed for %d texts", len(texts))
        raise


def embed_single(text: str) -> list[float]:
    """Generate a single dense embedding."""
    return embed_texts([text])[0]


# ── Sparse (BM25) Embedding ──────────────────────────────────────────
# Milvus 2.4+ supports SPARSE_FLOAT_VECTOR via built-in BM25 analyzer.
# The actual sparse embedding is generated server-side by Milvus when
# the collection schema includes a SPARSE_FLOAT_VECTOR field with BM25
# function. This function returns None as a sentinel — Milvus handles it.
# For client-side BM25, use the milvus_model library (future).


def embed_sparse(texts: list[str]) -> list[dict[int, float]]:
    """Generate BM25 sparse embeddings.

    NOTE: Milvus 2.4+ can auto-generate BM25 sparse vectors server-side
    via Function-based SPARSE_FLOAT_VECTOR fields. This client-side
    function is a placeholder. Real BM25 embedding requires:
      pip install milvus-model
      from milvus_model.sparse import BM25EmbeddingFunction
    """
    # Placeholder: return empty sparse vectors
    # The actual BM25 embedding will be generated by Milvus server-side
    # when we define the collection with a BM25 function.
    return [{} for _ in texts]
