<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.xu</groupId>
        <artifactId>mq-framework</artifactId>
        <version>${revision}</version>
    </parent>


    <artifactId>mq-producer-framework</artifactId>

    <name>mq-producer-framework</name>
    <description>mq发送者封装</description>

    <dependencies>
        <dependency>
            <groupId>org.xu</groupId>
            <artifactId>common</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.xu</groupId>
            <artifactId>mq-common-framework</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
    </dependencies>
</project>
